config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :chat_rooms do
        collection do
            get 'mine'
            get 'users'
            get 'salons'
            post 'destroy_user'
        end
    end

    resources :users_extend, :path => 'users', param: :id, only: [:destroy]
    resources :users_extend, :path => 'users', param: :id, only: [:update] do
        get 'update', :on => :member
    end


    root 'chat_rooms#index'

    mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)

        user ||= User.new

        if user.has_role? :simple_user
            can :read, :all
            can [:create, :mine], ChatRoom
            can [:update, :destroy], ChatRoom, {user_id: user.id}
        end

        can :manage, :all if user.has_role? :admin
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    resourcify
    belongs_to :user
    has_many :messages, dependent: :destroy
    validates :title, :presence => true

    def self.search(search)
        where("title LIKE ?", "%#{search}%")
    end
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :chat_room

    def timestamp
        created_at.strftime('%d/%m/%Y à %H:%M:%S')
    end

    validates :content, presence: true, length: {minimum: 2, maximum: 1000}
    after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
    rolify
    # Include default devise modules. Others available are:
    # :omniauthable, :lockable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable

    has_many :chat_rooms, dependent: :destroy
    has_many :messages, dependent: :destroy
    after_create :assign_default_role

    def assign_default_role
        self.add_role(:simple_user) if self.roles.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Aucune page n'est accessible si l'utilisateur n'est pas connecté
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
      devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    before_action :chat_rooms_search, only: [:index, :salons]
    load_and_authorize_resource

    def index
    end

    def show
        @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
        @message = Message.new
    end

    def mine
        if params[:search]
            @chat_rooms = current_user.chat_rooms.search(params[:search]).order("created_at DESC")
        else
            @chat_rooms = current_user.chat_rooms.order("created_at DESC")
        end
        render :mine
    end

    def new
        @chat_room = ChatRoom.new
    end

    def create
        if ChatRoom.exists?(title: @chat_room.title)
            flash[:danger] = "Ce salon existe déjà"
            redirect_to chat_rooms_path
        else
            @chat_room = current_user.chat_rooms.build(chat_room_params)
            if @chat_room.save
                flash[:success] = "Le salon a bien été crée"
                redirect_to chat_rooms_path
            else
                render 'new'
            end
        end
    end

    def users
        if params[:search]
            @users = User.search(params[:search]).order("id DESC").paginate(:page => params[:page], per_page: 10);
        else
            @users = User.all.order("id DESC").paginate(:page => params[:page], per_page: 10);
        end
        render :users
    end

    def salons
        render :salons
    end

    def edit
        session[:return_to] ||= request.referer
    end

    def update
        if @chat_room.update chat_room_params
            flash[:success] = "Le salon \"#{@chat_room.title}\" a bien été modifié."
            redirect_to session.delete(:return_to)
        else
            render 'edit'
        end
    end

    def destroy_user
        # flash[:success] = "L'utilsateur \"#{@user.username}\" a bien été supprimé."
        @user.destroy
        redirect_to users_chat_rooms_path
    end

    def destroy
        flash[:success] = "Le Salon \"#{@chat_room.title}\" a bien été supprimé."
        @chat_room.destroy
        redirect_to salons_chat_rooms_path
    end

    private

    def chat_room_params
        params.require(:chat_room).permit(:title)
    end

    def chat_rooms_search
        if params[:search]
            @chat_rooms = ChatRoom.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], per_page: 10);
        else
            @chat_rooms = ChatRoom.all.order("created_at DESC").paginate(:page => params[:page], per_page: 10);
        end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def show
      @messages = Message.all
  end
end

app/controllers/users_extend_controller.rb
class UsersExtendController < ApplicationController

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:success] = "Utilisateur supprimé."
      redirect_back(fallback_location: users_chat_rooms_path)
    end
  end

  def update
      user = User.find(params[:id])

      if user.has_role? :admin
          user.remove_role :admin
      else
          user.add_role :admin
      end
      redirect_to users_chat_rooms_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_color(name)
        return 'info' unless %w( success info danger warning ).include?(name)
        name
    end

    def role_label(role)
        if role == "simple_user"
          raw '<span class="label label-primary">Utilisateur</span>'
        elsif role == "admin"
          raw '<span class="label label-danger">Administrateur</span>'
        end
    end


    # def search_form(path)
    #     s = form_tag(path, :method => "get", id: "search-form") do
    #         p = text_field_tag :search, params[:search], placeholder: "Rechercher un salon"
    #         p << submit_tag "Rechercher", id: "submitSearch", class: "btn btn-info"
    #         p
    #     end
    #     s.html_safe
    # end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/chat_rooms/_chat_room.html.erb
<div class="circle">
    <%= link_to chat_room do %>
      <div class="category-first-letter"><%= chat_room.title.capitalize.chars.first %></div>
      <div class="category-title">#<%= chat_room.title.capitalize %></div>
    <% end %>
</div>

app/views/chat_rooms/edit.html.erb
<h1 class="super-title">Modifier un salon</h1>

<div class="content-centered">
    <%= simple_form_for @chat_room do |f| %>
        <div class="row">
            <div class="form-group col-lg-5">
                <p>
                    <%= f.input :title, label: 'Titre', class:'form-control' %>
                </p>
            </div>
        </div>

        <p>
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </p>
    <% end %>

    <% if current_user.has_role?(:admin) %>
        <%= link_to 'Aller à l\'administration', admin_chat_rooms_path, class: 'btn btn-info' %>
    <% end %>

</div>

app/views/chat_rooms/index.html.erb
<div class="col-lg-12">
    <h1 class="super-title">Sélectionnez un salon de chat</h1>
    <hr>
    <br><br>
    <%= render "layouts/search" %>
    <!-- Affiche la pagination seulement si il y a plus d'une page -->
    <% if @chat_rooms.count > 7 %>
        <%=  will_paginate @chat_rooms, renderer: BootstrapPagination::Rails %>
    <% end %>
    <br>
    <div class="circle">
        <%= link_to new_chat_room_path do %>
            <div class="category-first-letter">+</div>
            <div class="category-title">Ajouter une catégorie</div>
        <% end %>
    </div>

    <% if @chat_rooms.present? %>
        <%= render @chat_rooms %>
    <% else %>
        <% if params[:search].present? %>
            <p>Aucun salon ne correspond à cette recherche : <%= params[:search] %>.</p>
        <% else %>
            <p>Il n'y a aucun salon</p>
        <% end %>
    <% end %>
</div>

app/views/chat_rooms/mine.html.erb
<div class="col-lg-12">
    <h1 class="super-title">Mes salons</h1>
    <hr>

    <%= form_tag(mine_chat_rooms_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Rechercher un salon" %>
            <%= submit_tag "Recherche", id: "submitSearch", class: "btn btn-info" %>
    <% end %>

    <div class="circle">
        <%= link_to new_chat_room_path do %>
            <div class="category-first-letter">+</div>
            <div class="category-title">Ajouter une catégorie</div>
        <% end %>
    </div>

    <% if @chat_rooms.present? %>
        <%= render @chat_rooms %>
    <% else %>
        <p>Aucun salon ne correspond à cette recherche <%= params[:search] %>.</p>
    <% end %>
</div>

app/views/chat_rooms/new.html.erb
<h1 class="super-title">Add chat room</h1>
<hr>

<div class="content-centered">
  <%= form_for @chat_room do |f| %>
      <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      </div>

      <%= f.submit "Add!", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/chat_rooms/salons.html.erb
<div class="col-lg-12">
    <h1 class="super-title">Administration des salons</h1>

    <%= form_tag(salons_chat_rooms_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Rechercher un salon" %>
            <%= submit_tag "Recherche", id: "submitSearch", class: "btn btn-info" %>
    <% end %>


    <%=  will_paginate @chat_rooms, renderer: BootstrapPagination::Rails %>
    <% if @chat_rooms.present? %>
        <table class="table">
            <thead>
                <tr>
                    <th>Salon</th>
                    <th>Créateur</th>
                    <th>Date de création</th>
                    <th>Dernière mise à jour</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
                <% @chat_rooms.each do |chat_room| %>
                    <tr>
                        <td><%= chat_room.title %></td>
                        <td><%= chat_room.user.username %></td>
                        <td><%= chat_room.created_at.strftime("%d-%m-%Y") %></td>
                        <td><%= chat_room.updated_at.strftime("%d-%m-%Y") %></td>
                        <td>
                            <%= link_to 'Accéder', chat_room, class: 'btn btn-primary' %>
                            <%= link_to 'Modifier', edit_chat_room_path(chat_room), class: 'btn btn-warning' %>
                            <%= link_to 'Supprimer', chat_room, method: :delete, data: { confirm: 'Êtes vous sûr de supprimer ce salon ? Cette action est irréversible' }, class: 'btn btn-danger' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

    <% else %>
        <p>Aucun salon ne correspond à cette recherche <%= params[:search] %>.</p>
    <% end %>

</div>

app/views/chat_rooms/show.html.erb
<h1 class="super-title"><%= @chat_room.title %></h1>
<hr>

<%= form_tag(chat_rooms_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Rechercher un salon" %>
    <%= submit_tag "Recherche", id: "submitSearch", class: "btn btn-info" %>
<% end %>

<% if @chat_room.user_id == current_user.id %>
    <%= link_to('Modifier', edit_chat_room_path(@chat_room), class: 'btn btn-warning') %>
<% end %>

<div class="box" id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
</div>

<div class="content-centered">
    <%= form_for @message, url: '#' do |f| %>
    <hr>
    <div class="form-group">
        <%= f.label "Ajouter un message" %>
        <%= f.text_area :content, class: 'form-control' %>
    </div>

    <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
    <% end %><br>
</div>

app/views/chat_rooms/users.html.erb
<div class="col-lg-12">
    <h1 class="super-title">Administration des utilisateurs</h1>

    <%= form_tag(users_chat_rooms_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Rechercher un salon" %>
            <%= submit_tag "Recherche", id: "submitSearch", class: "btn btn-info" %>
    <% end %>


    <%=  will_paginate @users, renderer: BootstrapPagination::Rails %>
    <% if @users.present? %>
        <table class="table">
            <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Date d'inscription</th>
                    <th>Roles</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.username %></td>
                        <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
                        <td><%= role_label(user.roles.first.name) %>
                        </td>
                        <td>
                            <% if user.has_role? :admin %>
                                <%= link_to 'Remettre en utilisateur', users_extend_path(user), method: :put, data: { confirm: 'Êtes vous sûr d\'enlever les droits à cet utilisateur ?'}, class: 'btn btn-warning' %>
                            <% else %>
                                <%= link_to 'Promouvoir en admin', users_extend_path(user), method: :put, data: { confirm: 'Êtes vous sûr de promouvoir cet utilisateur admin ? '}, class: 'btn btn-warning' %>
                            <% end %>
                            <%= link_to 'Supprimer', users_extend_path(user),
                            method: :delete,
                            data: {
                                confirm: 'Êtes vous sûr de supprimer cet utilisateur ? Cette action est irréversible'
                            },
                            class: 'btn btn-danger' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

    <% else %>
        <p>Aucun salon ne correspond à cette recherche <%= params[:search] %>.</p>
    <% end %>

</div>

app/views/home/index.html.erb
<h1>
    <%= Rails.application.class.parent_name %> !
</h1>

<p>
    <%= link_to 'Listes des Messages', messages_path, class: 'btn btn-default' %>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Gowip</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <% if user_signed_in? %>
                    <% if current_user.has_role?(:admin) %>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">Administration <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to('Utilisateurs', users_chat_rooms_path) %></li>
                            <li><%= link_to('Salon', salons_chat_rooms_path) %></li>
                        </ul>
                    </li>
                    <% end %>

                    <li>
                        <%= link_to('Mes salons', mine_chat_rooms_path) %>
                    </li>
                    <li>
                        <%= link_to current_user.username, edit_user_registration_path %>
                    </li>
                    <li>
                        <%= link_to('Se deconnecter', destroy_user_session_path, :method => :delete) %>
                    </li>
                    <% else %>
                    <li>
                        <%= link_to('Se connecter', new_user_session_path)  %>
                    </li>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br>
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name %>">
    <a class="close" data-dismiss="alert">x</a>
    <%= content_tag :div, msg, id:"flash_#{name}" %>
</div>
<% end %>

<br>

app/views/layouts/_search.html.erb
<%= form_tag(chat_rooms_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Rechercher un salon" %>
        <%= submit_tag "Recherche", id: "submitSearch", class: "btn btn-info" %>
<% end %>
<!-- Création d'un helper pour générer ce code - incomplet -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
          <%= render "layouts/header" %>
          <p id="notice"><%= notice %></p>
          <%= yield %>
          <%= render "layouts/footer" %>
      </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="block">
    <div class="msg">
        <div class="author">
            <%= message.user.username %><span class="legend"> le <%= message.timestamp %></span>
            <div class="content">
                <%= message.content %>
            </div>
        </div>
    </div>
</div>
<hr>

app/views/room/show.html.erb
<h1>chat room</h1>

<div id="messages">
    <%= render @messages %>
</div>

<form>
    <input type="text" data-behaviour="room-speaker">
</form>